export const PREDICTION_MARKET_SUSD_ABI = [
  {
    inputs: [],
    name: "getMarketInfo",
    outputs: [
      { type: "string", name: "_question" },
      { type: "uint256", name: "_deadline" },
      { type: "bytes32", name: "_category" },
      { type: "uint8", name: "_status" },
      { type: "uint256", name: "_totalCollateral" },
      { type: "uint256", name: "_yesSupply" },
      { type: "uint256", name: "_noSupply" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOdds",
    outputs: [
      { type: "uint256", name: "yesOdds" },
      { type: "uint256", name: "noOdds" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "question",
    outputs: [{ type: "string", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deadline",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "category",
    outputs: [{ type: "bytes32", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "status",
    outputs: [{ type: "uint8", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "outcome",
    outputs: [{ type: "bool", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "resolutionConfidence",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCollateral",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feePercent",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "createdAt",
    outputs: [{ type: "uint256", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "susd",
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "yesToken",
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "noToken",
    outputs: [{ type: "address", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getResolutionSources",
    outputs: [{ type: "string[]", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "resolutionReasoning",
    outputs: [{ type: "string", name: "" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { type: "bool", name: "isYes" },
      { type: "uint256", name: "amount" },
    ],
    name: "bet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
